$VersionControl = 'git'
$VersionControlRepos = @(
	'git@github.com:iquipsys-positron/iqs-devenv'
	'git@github.com:iquipsys-positron/iqs-libs-clientshell-angular'
	'git@github.com:iquipsys-positron/iqs-libs-clientshell2-angular.git'
	'git@github.com:iquipsys-positron/iqs-libs-unsupported-angular.git'
	'git@github.com:iquipsys-positron/iqs-clients-landing-angular.git'
	'git@github.com:iquipsys-positron/iqs-clients-home-angular.git'
	'git@github.com:iquipsys-positron/iqs-clients-monitoring-angular.git'
	'git@github.com:iquipsys-positron/iqs-clients-retrospective-angular.git'
	'git@github.com:iquipsys-positron/iqs-clients-routes-angular.git'
	'git@github.com:iquipsys-positron/iqs-clients-statistics-angular.git'
	'git@github.com:iquipsys-positron/iqs-clients-incidents-angular.git'
	'git@github.com:iquipsys-positron/iqs-clients-schedule-angular.git'
	'git@github.com:iquipsys-positron/iqs-clients-usersettings-angular.git'
	'git@github.com:iquipsys-positron/iqs-clients-sensordata-angular.git'
	'git@github.com:iquipsys-positron/iqs-clients-manualcorrections-angular.git'
	'git@github.com:iquipsys-positron/iqs-clients-deviceconfig-angular.git'
	'git@github.com:iquipsys-positron/iqs-clients-emergencyconfig-angular.git'
	'git@github.com:iquipsys-positron/iqs-clients-eventconfig-angular.git'
	'git@github.com:iquipsys-positron/iqs-clients-objectconfig-angular.git'
	'git@github.com:iquipsys-positron/iqs-clients-orgconfig-angular.git'
	'git@github.com:iquipsys-positron/iqs-clients-zoneconfig-angular.git'
	'git@github.com:iquipsys-positron/iqs-clients-devicesimulator-angular.git'
	'git@github.com:iquipsys-positron/iqs-clients-dataprofiles-angular.git'
	'git@github.com:iquipsys-positron/iqs-clients-datamonitoring-angular.git'
)
$Package = 'npm'
$Build = 'none'
$Document = 'none'
$Test = 'none'
$Deploy = 'none'
