$VersionControl = 'git'
$VersionControlRepos = @(
    # 'git@gitlab.com:iqs-clients/iqs-client-shell.git'
    # 'git@gitlab.com:iqs-clients/iqs-client-positron-app.git'
    # 'git@gitlab.com:iqs-clients/iqs-simulator-app.git'
	# 'git@gitlab.com:iqs-clients/iqs-clients-shell2.git'
    # 'git@gitlab.com:iqs-clients/iqs-clients-config-devices-app.git'
    # 'git@gitlab.com:iqs-clients/iqs-clients-config-emergency-app.git'
    # 'git@gitlab.com:iqs-clients/iqs-clients-config-events-app.git'
	# 'git@gitlab.com:iqs-clients/iqs-clients-config-objects-app.git'
	# 'git@gitlab.com:iqs-clients/iqs-clients-config-site-app.git'
	# 'git@gitlab.com:iqs-clients/iqs-clients-config-zones-app.git'
	# 'git@gitlab.com:iqs-clients/iqs-clients-dottraces-app.git'
	# 'git@gitlab.com:iqs-clients/iqs-clients-home-app.git'
	# 'git@gitlab.com:iqs-clients/iqs-clients-incidents-app.git'
	# 'git@gitlab.com:iqs-clients/iqs-clients-manual-corrections-app.git'
	# 'git@gitlab.com:iqs-clients/iqs-clients-monitoring-app.git'
	# 'git@gitlab.com:iqs-clients/iqs-clients-retrospective-app.git'
	# 'git@gitlab.com:iqs-clients/iqs-clients-schedule-app.git'
	# 'git@gitlab.com:iqs-clients/iqs-clients-statistics-app.git'
	# 'git@gitlab.com:iqs-clients/iqs-clients-usersettings-app.git'
	# 'git@gitlab.com:iqs-clients/iqs-clients-unsupported-page.git'
)
$Package = 'npm'
$Build = 'none'
$Document = 'none'
$Test = 'none'
$Deploy = 'none'
