version: '3.3'

services:
  iqs-clients:
    build:
      context: ../
      dockerfile: ./docker/Nginx.Dockerfile
    environment:
      - IQS_SERVER_URL=http://192.168.99.100:8080
    ports: 
      - "80:80"
